# Vecteurs et matrices avec Numpy

* Numpy est un package pour Python spécilisé dans la manipulation des tableaux (array), essentiellement les vecteurs et les matrices.
* Le package propose un grand nombre de routines pour un accès rapide aux données (ex. recherche, extraction), pour les manipulations diverses (ex. tri), pour les calculs (ex. calcul statistique).

## 1. Création d'un vecteur

### 1.1. Création via une saisie manuelle

In [1]:
# importer le module numpy
# np alias pour accéder à la librairie numpy
import numpy as np

In [2]:
# création manuelle à partir d'un ensemble de valeurs
a=np.array([1.2, 2.5, 3.2, 1.8])

# affichage
print(a)

[ 1.2  2.5  3.2  1.8]


In [3]:
# type de structure
print(type(a))

# type de données
print(a.dtype)

# nombre de dimensions
print(a.ndim)

# nombre de lignes et de colonnes
print(a.shape)

# nombre totale de valeurs
print(a.size)

<class 'numpy.ndarray'>
float64
1
(4,)
4


In [4]:
# Création de typage implicite

b=np.array([1,2,4])
print(b.dtype)

int64


In [5]:
b=np.array([1,2,4],dtype=float)
print(b.dtype)

float64


In [6]:
c=np.array([True, False, False])
print(c.dtype)

bool


In [7]:
d=np.array([{"A":(45, 200)}, {"B":(34, 150)}])
print(d)
print(d.dtype)

[{'A': (45, 200)} {'B': (34, 150)}]
object


### 1.2. Création d'une séquence de valeurs

In [8]:
# suite arithmétique de raison 1
a=np.arange(start=0,stop=10)
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [9]:
# suite arithmétique de raison step
a=np.arange(start=0,stop=10, step=2)
print(a)

[0 2 4 6 8]


In [10]:
# vecteur de valeurs identiques 1
a=np.ones(shape=5)
print(a)

[ 1.  1.  1.  1.  1.]


In [11]:
# répétition de la même valeur
a=np.full(shape=5, fill_value=3.2)
print(a)

[ 3.2  3.2  3.2  3.2  3.2]


In [12]:
# charger à partir d'un fichier
a=np.loadtxt("vecteur.txt", dtype=float)
print(a)

[  3.   5.  17.   5.  35.]


In [13]:
# conversion d'une collection en type array

# liste de valeurs
lst=[1.2, 3.1, 4.5]
print(type(lst))

# conversion à partir d'une liste
a = np.asarray(lst,dtype=float)
print(a)
print(type(a))

<class 'list'>
[ 1.2  3.1  4.5]
<class 'numpy.ndarray'>


### 1.3. Redimensionnement


In [14]:
# vecteur de valeurs
a=np.array([1.2,2.5,3.2,1.8])
print(a)

[ 1.2  2.5  3.2  1.8]


In [15]:
# ajouter une valeur, placée en dernière position
a=np.append(a,10)
print(a)

[  1.2   2.5   3.2   1.8  10. ]


In [16]:
# suppression via indice
b=np.delete(a,2)
print(b)

[  1.2   2.5   1.8  10. ]


In [17]:
# redimensionnement (les nouvelles cases mises à 0)
a=np.array([1,2,3])
a.resize(1,5)
print(a)

[[1 2 3 0 0]]


In [18]:
# concatenation
x=np.array([1,2,5,6])
y=np.array([2,1,7])
z=np.append(x,y)
print(z)

[1 2 5 6 2 1 7]


## 2. Extraction des valeurs d'un vecteur

### 2.1. Accès indicé

In [19]:
v=np.array([1.2, 7.4, 4.2, 8.5, 6.3])
print(v)

[ 1.2  7.4  4.2  8.5  6.3]


In [20]:
# première valeur
print(v[0])

1.2


In [21]:
# dernière valeur
print(v[-1])

6.3


In [22]:
# palge d'indices (3 non-inclus)
print(v[1:3])

[ 7.4  4.2]


In [23]:
# extrêms, début à 3 (non-inclus)
print(v[:3])

[ 1.2  7.4  4.2]


In [24]:
# extrêmes, 2 à fin
print(v[2:])

[ 4.2  8.5  6.3]


In [25]:
# indices négatifs 
print(v[-3:]) # 3 derniers éléments

[ 4.2  8.5  6.3]


In [26]:
# valeur de 1 à 3 avec un pas 1 (implicitement le pas est 1)
print(v[1:4:1])

[ 7.4  4.2  8.5]


In [27]:
# de 0 à 2 avec un pas de 2
print(v[0:3:2])

[ 1.2  4.2]


In [28]:
# le pas peut être négatif, de 3 à 1 avec un pas de -1
print(v[3:0:-1])

[ 8.5  4.2  7.4]


In [29]:
# inverser un vecteur
print(v[::-1])

[ 6.3  8.5  4.2  7.4  1.2]


### 2.2. Accès par conditions

In [30]:
# extraction avec un vecteur de booléens
b=np.array([False, True, False, True, False],dtype=bool)
print(v[b])

[ 7.4  8.5]


In [31]:
# condition pour l'extraction
print(v[v<7])

[ 1.2  4.2  6.3]


In [32]:
# on peut utiliser extract()
print(np.extract(v<7,v))

[ 1.2  4.2  6.3]


In [33]:
# la condition est un vecteur de booléen
b=v<7
print(b)

[ True False  True False  True]


In [34]:
# valeur maximale
print(np.max(v))
# même chose pour min()

8.5


In [35]:
# indice de la valeur maximale
print(np.argmax(v))

3


In [36]:
# tri de valeurs
print(np.sort(v))

[ 1.2  4.2  6.3  7.4  8.5]


In [37]:
# récupération des indices triés
print(np.argsort(v))

[0 2 4 1 3]


In [38]:
# valeurs distinctes
a=np.array([1,2,2,2,1,1,2])
print(np.unique(a))

[1 2]


## 3. Calculs sur les vecteurs

In [39]:
# moyenne
print(np.mean(v))

5.52


In [40]:
# médiane
print(np.median(v))

6.3


In [41]:
# variance
print(np.var(v))

6.6856


In [42]:
# écrat type
print(np.std(v))

2.58565272223


In [43]:
# quantile
print(np.percentile(v,50)) # (50%=médiane)

6.3


In [44]:
# somme
print(np.sum(v))

27.6


In [45]:
# somme cumulée
print(np.cumsum(v))

[  1.2   8.6  12.8  21.3  27.6]


In [46]:
# multiplication de deux vecteurs (terme à terme)
x=np.array([1.2, 1.3, 1.0])
y=np.array([2.1, 0.8, 1.3])
print(x*y)

[ 2.52  1.04  1.3 ]


In [47]:
# somme
print(x+y)

[ 3.3  2.1  2.3]


In [48]:
# multiplication par un scalaire
print(2*x)

[ 2.4  2.6  2. ]


In [49]:
# produit scalaire
w=np.vdot(x,y)
print(w)

4.86


In [50]:
# ou bien
print(np.sum(x*y))

4.86


In [51]:
# norme d'un vecteur
n=np.linalg.norm(x)
print(n)

2.03224014329


In [52]:
# ou bien
import math
print(math.sqrt(np.sum(x**2)))

2.0322401432901573


In [53]:
# comparaison
z=x>y
print(z)

[False  True False]


In [54]:
# opérations logiques
a=np.array([True,True,False,True],dtype=bool)
b=np.array([True,False,True,False],dtype=bool)
# ET logique
c=np.logical_and(a,b)
print(c)

[ True False False False]


In [55]:
# OU exclusif logique
np.logical_xor(a,b)

array([False,  True,  True,  True], dtype=bool)

In [56]:
# opérations ensemblistes
x=np.array([1,2,5,7])
y=np.array([2,4,6,1])

# intersection
print(np.intersect1d(x,y))

[1 2]


In [57]:
# union
print(np.union1d(x,y))

[1 2 4 5 6 7]


In [58]:
# différence, c-à-d qui sont dans x et pas dans y
print(np.setdiff1d(x,y))

[5 7]


## 4. Création d'une matrice

In [59]:
##### création manuelle à partir d'un ensemble de valeurs
a=np.array([[1.2,2.5],[3.2, 1.8],[1.1,4.3]])

# affichage
print(a)

[[ 1.2  2.5]
 [ 3.2  1.8]
 [ 1.1  4.3]]


In [60]:
# type de structure
print(type(a))

# type de données
print(a.dtype)

# nombre de dimensions
print(a.ndim)

# nombre de lignes et de colonnes
print(a.shape)

# nombre totale de valeurs
print(a.size)

<class 'numpy.ndarray'>
float64
2
(3, 2)
6


In [61]:
# création et typage implicite
a=np.array([[1,2],[4,7]])
print(a.dtype)

int64


In [62]:
# création et typage explicite
a=np.array([[1,2],[4,7]],dtype=float)
print(a.dtype)

float64


In [63]:
# création à partir d'une séquence
# arange() génère une séquence de valeurs
# reshape() se charge de les réorganiser en des lignes et des colonnes
a=np.arange(0,10).reshape(2,5)
print(a)

[[0 1 2 3 4]
 [5 6 7 8 9]]


In [64]:
# un vecetur peut être converti en matrice
a=np.array([2.1,3.4,6.7,8.1,3.5,7.2])
print(a.shape)

(6,)


In [65]:
# redimensionner en 3 lignes et 2 colonnes
b=a.reshape(3,2)
print(b.shape)
print(b)

(3, 2)
[[ 2.1  3.4]
 [ 6.7  8.1]
 [ 3.5  7.2]]


In [66]:
# metrices de valeurs identiques
# ex. pour initialisation
a=np.zeros(shape=(2,4))
print(a)

[[ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]]


In [67]:
# plus généralement
a=np.full(shape=(2,4),fill_value=0.1)
print(a)

[[ 0.1  0.1  0.1  0.1]
 [ 0.1  0.1  0.1  0.1]]


In [68]:
# charger à partir d'un fichier, typage explicite
# séparateur de colonne=tabulation="\t"
a=np.loadtxt("matrice.txt",delimiter="\t",dtype=float)
print(a)

[[  45.   62.  168.]
 [  34.   68.  187.]
 [  53.   85.  169.]]


In [69]:
# matrice valeurs
a=np.array([[1.2,2.5],[3.2,1.8],[1.1,4.3]])
print(a)

[[ 1.2  2.5]
 [ 3.2  1.8]
 [ 1.1  4.3]]


In [70]:
# ajouter une ligne
b=np.array([[4.1,2.6]])
c=np.append(a,b,axis=0)
print(c)

[[ 1.2  2.5]
 [ 3.2  1.8]
 [ 1.1  4.3]
 [ 4.1  2.6]]


In [71]:
# ajouter une colonne
d=np.array([[7.8],[6.1],[5.4]])
print(np.append(a,d,axis=1))

[[ 1.2  2.5  7.8]
 [ 3.2  1.8  6.1]
 [ 1.1  4.3  5.4]]


In [72]:
# insertion
print(np.insert(a,2,b,axis=0))

[[ 1.2  2.5]
 [ 3.2  1.8]
 [ 4.1  2.6]
 [ 1.1  4.3]]


In [73]:
# suppression
print(np.delete(a,1,axis=0))

[[ 1.2  2.5]
 [ 1.1  4.3]]


In [74]:
# modifier la dimension d'une matrice existante
# parcout les données ligne par ligne
h=np.resize(a,new_shape=(2,3))
print(h)

[[ 1.2  2.5  3.2]
 [ 1.8  1.1  4.3]]


## 5. Extraction des valeurs

In [75]:
v=np.array([[1, 5],[3,8],[0,4]])
print(v)

[[1 5]
 [3 8]
 [0 4]]


In [76]:
# accès indicé - première valeur
print(v[0,0])

1


In [77]:
# toutes les lignes et toutes les colonnes
print(v[:,:])

[[1 5]
 [3 8]
 [0 4]]


In [78]:
# lignes 0 et 1 (2 non inclus), toutes les colonnes
print(v[0:2,:])

[[1 5]
 [3 8]]


In [79]:
# ligne 1 à la dernière
print(v[1:,:])

[[3 8]
 [0 4]]


In [80]:
# dernière ligne et toutes les colonnes
print(v[-1,:])

[0 4]


In [81]:
# les deux dernières lignes 
print(v[-2:,:])

[[3 8]
 [0 4]]


In [82]:
# calculer la somme des colonnes pour chaque ligne
s=np.sum(v,axis=1)
print(s)

[ 6 11  4]


In [83]:
# repérer les lignes dont la somme est égale au minimum
b=(s==np.min(s))
print(b)

[False False  True]


In [84]:
# application du filtre booléen
print(v[b,:])

[[0 4]]


In [85]:
# recherche de la valeur max des lignes pour chaque colonne
print(np.max(v,axis=0))

[3 8]


In [86]:
# recherche de la valeur max des colonnes pour chaque ligne
print(np.max(v,axis=1))

[5 8 4]


In [87]:
# recherche de l'indice de valeur max des lignes pour chaque colonne
print(np.argmax(v,axis=0))

[1 1]


In [88]:
# tri des lignes pour chaque colonne
print(np.sort(v,axis=0))

[[0 4]
 [1 5]
 [3 8]]


In [89]:
# récupération des indices triés
print(np.argsort(v,axis=0))

[[2 2]
 [0 0]
 [1 1]]


In [90]:
v=np.array([[1.2,2.5],[3.2,1.8],[1.1,4.3]])
print(v)

[[ 1.2  2.5]
 [ 3.2  1.8]
 [ 1.1  4.3]]


In [91]:
# avec les indices, on peut accéder aux valeurs de la matrice
# boucles indicées
s=0.0
for i in range(0,v.shape[0]):
    for j in range(0,v.shape[1]):
        print(v[i,j])
        s=s+v[i,j]
print("Somme=",s)

1.2
2.5
3.2
1.8
1.1
4.3
Somme= 14.1


In [92]:
# itérateur - accès ligne par ligne
# pas besoin des indices
s=0.0
for x in np.nditer(v):
    print(x)
    s=s+x
print("Somme=",s)

1.2
2.5
3.2
1.8
1.1
4.3
Somme= 14.1


In [93]:
# itérateur - accès colonne par colonne
s=0.0
for x in np.nditer(v,order="F"):
    print(x)
    s=s+x
print("Somme=",s)

1.2
3.2
1.1
2.5
1.8
4.3
Somme= 14.1


## 6. Calcul matriciel

In [94]:
x=np.array([[1.2,2.5],[3.2,1.8],[1.1,4.3]])
y=np.array([[2.1,0.8],[1.3,2.5]])
print(x)
print(y)

[[ 1.2  2.5]
 [ 3.2  1.8]
 [ 1.1  4.3]]
[[ 2.1  0.8]
 [ 1.3  2.5]]


In [95]:
# transposition
print(np.transpose(x))

[[ 1.2  3.2  1.1]
 [ 2.5  1.8  4.3]]


In [96]:
# multiplication
print(np.dot(x,y))

[[  5.77   7.21]
 [  9.06   7.06]
 [  7.9   11.63]]


In [97]:
# déterminant
print(np.linalg.det(y))

4.21


In [98]:
# inversion
print(np.linalg.inv(y))

[[ 0.59382423 -0.19002375]
 [-0.3087886   0.49881235]]


In [99]:
# Résolution de système linéaire y.a=z
z=np.array([1.7,1.0])
print(np.linalg.solve(y,z))

[ 0.81947743 -0.02612827]


In [100]:
# vérification a=y^(-1).z
print(np.dot(np.linalg.inv(y),z))

[ 0.81947743 -0.02612827]


In [101]:
# matrice symétrique avec x^t.x
s=np.dot(np.transpose(x),x)
print(s)

[[ 12.89  13.49]
 [ 13.49  27.98]]


In [102]:
# valeurs et vecteurs propres
print(np.linalg.eigh(s))

(array([  4.97837925,  35.89162075]), array([[-0.86259502,  0.50589508],
       [ 0.50589508,  0.86259502]]))
